<?php

use Drupal\Core\Routing\RouteMatchInterface;
use \Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_page_attachments().
 */
function age_checker_page_attachments_alter(array &$attachments) {

$attachments['#attached']['library'][] = 'js/age_checker';
  // $attachments['#attached']['library'][] = array('age_checker', 'admin');
  // $form['#attached']['library'][] = array('webform', 'admin');
}
