<?php

use Drupal\Core\Routing\RouteMatchInterface;
use \Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_page_attachments().
 */
function age_checker_page_attachments_alter(array &$attachments) {

$attachments['#attached']['library'][] = 'js/age_checker';
  // $attachments['#attached']['library'][] = array('age_checker', 'admin');
  // $form['#attached']['library'][] = array('webform', 'admin');
}

/**
 * Get the country name for Age Gate.
 */
function age_checker_get_country_name() {

  // Get the country code.
  dpm("inside age checker function");
  $country_code = age_checker_get_country_code();
  dpm("country code");
  dpm($country_code);exit;
//  // Get the default country.
//  $default_country = \Drupal::state(('age_checker_default_country');
//
//  $countries = \Drupal::state(('age_checker_countries', '');
//  $countries = explode("\n", $countries);
//  foreach ($countries as $country) {
//    $country_array = explode('|', $country);
//    if (trim($country_array[0]) == $country_code) {
//      $country_name = $country_code;
//      break;
//    }
//    else {
//      $country_name = $default_country;
//    }
//  }
//  return $country_name;
}

/**
 * Get the country code.
 */
function age_checker_get_country_code() {
  dpm("inside age_checker_get_country_code");
//  $ip_address = ip_address();
//  $ip_address = Drupal\age_checker\EventSubscriber\AgeCheckerSubscriber::_get_ip_address();
//  dpm("ip address");exit;
//  dpm($ip_address);exit;
//  $url = \Drupal::state('age_checker_country_code_url') . $ip_address;
//  $geoip_data = age_checker_get_geoip_data($url);
//
//  if (is_array($geoip_data)) {
//    $country_code = $geoip_data['country']['code'];
//  }
//  else {
//    $country_code = \Drupal::state('age_checker_default_country');
//  }
//  return $country_code;
}